'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://service/", ConfigurationName:="ServiceReference1.BanqueService")>  _
    Public Interface BanqueService
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function addCompte(ByVal request As ServiceReference1.addCompte) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.addCompteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function addCompteAsync(ByVal request As ServiceReference1.addCompte) As System.Threading.Tasks.Task(Of ServiceReference1.addCompteResponse)
        
        'CODEGEN: Parameter 'code1' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function virement(ByVal request As ServiceReference1.virement) As ServiceReference1.virementResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function virementAsync(ByVal request As ServiceReference1.virement) As System.Threading.Tasks.Task(Of ServiceReference1.virementResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listComptes(ByVal request As ServiceReference1.listComptes) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.listComptesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function listComptesAsync(ByVal request As ServiceReference1.listComptes) As System.Threading.Tasks.Task(Of ServiceReference1.listComptesResponse)
        
        'CODEGEN: Parameter 'code' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function retirer(ByVal request As ServiceReference1.retirer) As ServiceReference1.retirerResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function retirerAsync(ByVal request As ServiceReference1.retirer) As System.Threading.Tasks.Task(Of ServiceReference1.retirerResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCompte(ByVal request As ServiceReference1.getCompte) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.getCompteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getCompteAsync(ByVal request As ServiceReference1.getCompte) As System.Threading.Tasks.Task(Of ServiceReference1.getCompteResponse)
        
        'CODEGEN: Parameter 'code' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function verser(ByVal request As ServiceReference1.verser) As ServiceReference1.verserResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function verserAsync(ByVal request As ServiceReference1.verser) As System.Threading.Tasks.Task(Of ServiceReference1.verserResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service/")>  _
    Partial Public Class compte
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codeField As Long
        
        Private codeFieldSpecified As Boolean
        
        Private date_creationField As Date
        
        Private date_creationFieldSpecified As Boolean
        
        Private soldeField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property code() As Long
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
                Me.RaisePropertyChanged("code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codeSpecified() As Boolean
            Get
                Return Me.codeFieldSpecified
            End Get
            Set
                Me.codeFieldSpecified = value
                Me.RaisePropertyChanged("codeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property date_creation() As Date
            Get
                Return Me.date_creationField
            End Get
            Set
                Me.date_creationField = value
                Me.RaisePropertyChanged("date_creation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property date_creationSpecified() As Boolean
            Get
                Return Me.date_creationFieldSpecified
            End Get
            Set
                Me.date_creationFieldSpecified = value
                Me.RaisePropertyChanged("date_creationSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property solde() As Double
            Get
                Return Me.soldeField
            End Get
            Set
                Me.soldeField = value
                Me.RaisePropertyChanged("solde")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="addCompte", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class addCompte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public solde As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal solde As Double)
            MyBase.New
            Me.solde = solde
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="addCompteResponse", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class addCompteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As ServiceReference1.compte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.compte)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="virement", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class virement
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public code1 As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public code2 As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public montant As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal code1 As Long, ByVal code2 As Long, ByVal montant As Double)
            MyBase.New
            Me.code1 = code1
            Me.code2 = code2
            Me.montant = montant
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="virementResponse", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class virementResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listComptes", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class listComptes
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listComptesResponse", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class listComptesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return]() As ServiceReference1.compte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As ServiceReference1.compte)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="retirer", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class retirer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public code As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg1 As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal code As Long, ByVal arg1 As Double)
            MyBase.New
            Me.code = code
            Me.arg1 = arg1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="retirerResponse", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class retirerResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getCompte", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class getCompte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public code As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal code As Long)
            MyBase.New
            Me.code = code
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getCompteResponse", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class getCompteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As ServiceReference1.compte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.compte)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verser", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class verser
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public code As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public montant As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal code As Long, ByVal montant As Double)
            MyBase.New
            Me.code = code
            Me.montant = montant
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verserResponse", WrapperNamespace:="http://service/", IsWrapped:=true)>  _
    Partial Public Class verserResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface BanqueServiceChannel
        Inherits ServiceReference1.BanqueService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BanqueServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.BanqueService)
        Implements ServiceReference1.BanqueService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_addCompte(ByVal request As ServiceReference1.addCompte) As ServiceReference1.addCompteResponse Implements ServiceReference1.BanqueService.addCompte
            Return MyBase.Channel.addCompte(request)
        End Function
        
        Public Function addCompte(ByVal solde As Double) As ServiceReference1.compte
            Dim inValue As ServiceReference1.addCompte = New ServiceReference1.addCompte()
            inValue.solde = solde
            Dim retVal As ServiceReference1.addCompteResponse = CType(Me,ServiceReference1.BanqueService).addCompte(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_addCompteAsync(ByVal request As ServiceReference1.addCompte) As System.Threading.Tasks.Task(Of ServiceReference1.addCompteResponse) Implements ServiceReference1.BanqueService.addCompteAsync
            Return MyBase.Channel.addCompteAsync(request)
        End Function
        
        Public Function addCompteAsync(ByVal solde As Double) As System.Threading.Tasks.Task(Of ServiceReference1.addCompteResponse)
            Dim inValue As ServiceReference1.addCompte = New ServiceReference1.addCompte()
            inValue.solde = solde
            Return CType(Me,ServiceReference1.BanqueService).addCompteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_virement(ByVal request As ServiceReference1.virement) As ServiceReference1.virementResponse Implements ServiceReference1.BanqueService.virement
            Return MyBase.Channel.virement(request)
        End Function
        
        Public Sub virement(ByVal code1 As Long, ByVal code2 As Long, ByVal montant As Double)
            Dim inValue As ServiceReference1.virement = New ServiceReference1.virement()
            inValue.code1 = code1
            inValue.code2 = code2
            inValue.montant = montant
            Dim retVal As ServiceReference1.virementResponse = CType(Me,ServiceReference1.BanqueService).virement(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_virementAsync(ByVal request As ServiceReference1.virement) As System.Threading.Tasks.Task(Of ServiceReference1.virementResponse) Implements ServiceReference1.BanqueService.virementAsync
            Return MyBase.Channel.virementAsync(request)
        End Function
        
        Public Function virementAsync(ByVal code1 As Long, ByVal code2 As Long, ByVal montant As Double) As System.Threading.Tasks.Task(Of ServiceReference1.virementResponse)
            Dim inValue As ServiceReference1.virement = New ServiceReference1.virement()
            inValue.code1 = code1
            inValue.code2 = code2
            inValue.montant = montant
            Return CType(Me,ServiceReference1.BanqueService).virementAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_listComptes(ByVal request As ServiceReference1.listComptes) As ServiceReference1.listComptesResponse Implements ServiceReference1.BanqueService.listComptes
            Return MyBase.Channel.listComptes(request)
        End Function
        
        Public Function listComptes() As ServiceReference1.compte()
            Dim inValue As ServiceReference1.listComptes = New ServiceReference1.listComptes()
            Dim retVal As ServiceReference1.listComptesResponse = CType(Me,ServiceReference1.BanqueService).listComptes(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_listComptesAsync(ByVal request As ServiceReference1.listComptes) As System.Threading.Tasks.Task(Of ServiceReference1.listComptesResponse) Implements ServiceReference1.BanqueService.listComptesAsync
            Return MyBase.Channel.listComptesAsync(request)
        End Function
        
        Public Function listComptesAsync() As System.Threading.Tasks.Task(Of ServiceReference1.listComptesResponse)
            Dim inValue As ServiceReference1.listComptes = New ServiceReference1.listComptes()
            Return CType(Me,ServiceReference1.BanqueService).listComptesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_retirer(ByVal request As ServiceReference1.retirer) As ServiceReference1.retirerResponse Implements ServiceReference1.BanqueService.retirer
            Return MyBase.Channel.retirer(request)
        End Function
        
        Public Sub retirer(ByVal code As Long, ByVal arg1 As Double)
            Dim inValue As ServiceReference1.retirer = New ServiceReference1.retirer()
            inValue.code = code
            inValue.arg1 = arg1
            Dim retVal As ServiceReference1.retirerResponse = CType(Me,ServiceReference1.BanqueService).retirer(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_retirerAsync(ByVal request As ServiceReference1.retirer) As System.Threading.Tasks.Task(Of ServiceReference1.retirerResponse) Implements ServiceReference1.BanqueService.retirerAsync
            Return MyBase.Channel.retirerAsync(request)
        End Function
        
        Public Function retirerAsync(ByVal code As Long, ByVal arg1 As Double) As System.Threading.Tasks.Task(Of ServiceReference1.retirerResponse)
            Dim inValue As ServiceReference1.retirer = New ServiceReference1.retirer()
            inValue.code = code
            inValue.arg1 = arg1
            Return CType(Me,ServiceReference1.BanqueService).retirerAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_getCompte(ByVal request As ServiceReference1.getCompte) As ServiceReference1.getCompteResponse Implements ServiceReference1.BanqueService.getCompte
            Return MyBase.Channel.getCompte(request)
        End Function
        
        Public Function getCompte(ByVal code As Long) As ServiceReference1.compte
            Dim inValue As ServiceReference1.getCompte = New ServiceReference1.getCompte()
            inValue.code = code
            Dim retVal As ServiceReference1.getCompteResponse = CType(Me,ServiceReference1.BanqueService).getCompte(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_getCompteAsync(ByVal request As ServiceReference1.getCompte) As System.Threading.Tasks.Task(Of ServiceReference1.getCompteResponse) Implements ServiceReference1.BanqueService.getCompteAsync
            Return MyBase.Channel.getCompteAsync(request)
        End Function
        
        Public Function getCompteAsync(ByVal code As Long) As System.Threading.Tasks.Task(Of ServiceReference1.getCompteResponse)
            Dim inValue As ServiceReference1.getCompte = New ServiceReference1.getCompte()
            inValue.code = code
            Return CType(Me,ServiceReference1.BanqueService).getCompteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_verser(ByVal request As ServiceReference1.verser) As ServiceReference1.verserResponse Implements ServiceReference1.BanqueService.verser
            Return MyBase.Channel.verser(request)
        End Function
        
        Public Sub verser(ByVal code As Long, ByVal montant As Double)
            Dim inValue As ServiceReference1.verser = New ServiceReference1.verser()
            inValue.code = code
            inValue.montant = montant
            Dim retVal As ServiceReference1.verserResponse = CType(Me,ServiceReference1.BanqueService).verser(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_BanqueService_verserAsync(ByVal request As ServiceReference1.verser) As System.Threading.Tasks.Task(Of ServiceReference1.verserResponse) Implements ServiceReference1.BanqueService.verserAsync
            Return MyBase.Channel.verserAsync(request)
        End Function
        
        Public Function verserAsync(ByVal code As Long, ByVal montant As Double) As System.Threading.Tasks.Task(Of ServiceReference1.verserResponse)
            Dim inValue As ServiceReference1.verser = New ServiceReference1.verser()
            inValue.code = code
            inValue.montant = montant
            Return CType(Me,ServiceReference1.BanqueService).verserAsync(inValue)
        End Function
    End Class
End Namespace
